services:
  api:
    build:
      context: ./server
    container_name: closet_ai_api
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app

  worker:
    build:
      context: ./server
    container_name: closet_ai_worker
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - minio
    command: celery -A app.worker worker --loglevel=INFO
    volumes:
      - ./server:/app
      - app_venv:/app/.venv

  redis:
    image: redis:7-alpine
    container_name: closet_ai_redis
    ports:
      - "6379:6379"

  db:
    image: pgvector/pgvector:pg15
    container_name: closet_ai_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: pgvector/pgvector:pg15
    container_name: closet_ai_db_test
    profiles: [test]
    environment:
      POSTGRES_DB: closet_ai_test
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: closet_ai_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb -p local/${MINIO_BUCKET_NAME};
      exit 0;
      "

volumes:
  pgdata:
  minio_data:
  app_venv: